environment: dev
db:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:memory-dev:wordsmem
  username: sa
  password: sa
  hibernate.dialect: com.baeldung.dialect.SQLiteDialect
  hibernate.hbm2ddl.auto: create-drop
  hibernate.show_sql: true
