environment: prod
db:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:memory:wordsmem
  username: sa
  password: sa
  hibernate.dialect: com.sky.dialect.SQLiteDialect
  hibernate.hbm2ddl.auto: create-drop
  hibernate.show_sql: true
index:
  indexPath: lucene:index
